version: '2.1'

services: 
  database:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=plataformaactiva
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
  spring-boot:
    image: calvarezs/mingeso-project
    depends_on:
      - database
    ports:
      - 8787:8082
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=username
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=plataformaactiva
      - DATABASE_PORT=3306