version: '2'

services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

  # mariadb:
  #   image: 'bitnami/mariadb:latest' 
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=bn_testlink
  #     - MARIADB_DATABASE=bitnami_testlink
  #     - MARIADB_ROOT_PASSWORD=root
  #     - MARIADB_DATABASE=bugtracker
  #     - MARIADB_USER=mantisbt
  #     - MARIADB_PASSWORD=mantisbt
  #   volumes:
  #     - 'mariadb_data:/bitnami'

  # testlink:
  #   image: 'bitnami/testlink:latest'
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - 'testlink_data:/bitnami'
  #   depends_on:
  #     - mariadb
  #   environment:
  #     - MARIADB_HOST=mariadb
  #     - MARIADB_PORT_NUMBER=3307
  #     - TESTLINK_DATABASE_USER=bn_testlink
  #     - TESTLINK_DATABASE_NAME=bitnami_testlink
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - TESTLINK_USERNAME=admin
  #     - TESTLINK_PASSWORD=verysecretadminpassword
  #     - TESTLINK_EMAIL=admin@example.com

  # mariadb:
  #   image: 'bitnami/mariadb:latest'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=bn_testlink
  #     - MARIADB_DATABASE=bitnami_testlink
  #   volumes:
  #     - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=admin
      - TESTLINK_EMAIL=admin@example.com

  mantisbt:
    image: vimagick/mantisbt:latest
    ports:
      - "8989:80"
    links:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always
  
  database:
    image: mariadb:latest
    restart: always
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=plataformaactiva
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
