version: '2'

services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - 'mariadb_data:/bitnami'

  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    links:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - SMTP_ENABLE=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=carlos.alvarez.s@usach.cl
      - SMTP_PASSWORD=1C1C2L3Y5R8
      - SMTP_CONNECTION_MODE=tls
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=admin

  mantisbt:
    image: vimagick/mantisbt:latest
    ports:
      - "8989:80"
    links:
      - mariadb_mantis
    #volumes:
    #  - ~/MingesoG1/mantis-persistence:/var/www/html
    restart: always

  mariadb_mantis:
    image: mariadb:latest
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    ports:
      - '3366:3306'
    #volumes:
    #  - ~/MingesoG1/mantis-mariadb-persistence:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
