version: '3'

services: 
  database:
    image: mariadb:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=plataformaactiva
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password 
    ports:
      - "3306:3306" 
    restart: always 

  springboot:
    build: 
      context: .
      args: 
        URL: https://${GIT_USER}:${GIT_PASSWORD}@github.com/HectorPerezM/Mingeso-Grupo1
        BRANCH: CIPlatform
        PROJECT_FOLDER: backend
        ARTIFACT_ID: MINGESO
        VERSION: 1.0-SNAPSHOT
    links:
      - database
    ports:
      - "8282:8082" 
       