version: '2'

services: 
  database:
    image: mariadb:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=plataformaactiva
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password